# NumPy Arrays

NumPy is python library used for working with multi dimensional arrays and matrices along with a large collection of mathematical functions to operate on these arrays.
## Array of data
Importing the library and creating the first array,

In [2]:
import numpy as np

In [3]:
factorial = np.array([1,2,6,24,120,720])
factorial

array([  1,   2,   6,  24, 120, 720])

Type of array,

In [4]:
type(factorial)

numpy.ndarray

Two dimensions array,

In [5]:
np.array([[3,4],[5,6],[7,8]])

array([[3, 4],
       [5, 6],
       [7, 8]])

List comprehension array with numpy,

In [6]:
np.array([n for n in range(1,30,2)])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## Array attributes
Working with 2 different types of arrays and dtype, shape, itemsize functions,

In [7]:
intarray = np.array([[9,10,11,12],[8,7,6,5]])
intarray

array([[ 9, 10, 11, 12],
       [ 8,  7,  6,  5]])

In [8]:
floatarray = np.array([[9**(1/2),10**(1/2),3.33],[10/3,3.4,3.03],[25,50,75]])
floatarray

array([[ 3.        ,  3.16227766,  3.33      ],
       [ 3.33333333,  3.4       ,  3.03      ],
       [25.        , 50.        , 75.        ]])

Type of array with dtype function,

In [9]:
intarray.dtype

dtype('int64')

In [10]:
floatarray.dtype

dtype('float64')

Dimension of array with ndim, dimension es about the amount of dimension of array, example: 
1 dimension = []
2 dimensions = [[],[]]
3 dimensions = [[[],[]],[[],[]]]

In [11]:
intarray.ndim

2

In [12]:
floatarray.ndim

2

Shape of array with shape function, shape is about the amount of columns and rows that the arrays has,

In [13]:
intarray.shape

(2, 4)

In [14]:
floatarray.shape

(3, 3)

Size and itemsize let to know the number of elements inside an array and the bytes to be stored,

In [15]:
intarray.size

8

In [16]:
intarray.itemsize

8

In [17]:
floatarray.size

9

In [18]:
floatarray.itemsize

8

Iterating with arrays, printing all elements,

In [19]:
for row in intarray:
    for elements in row:
        print(elements, end=', ')

9, 10, 11, 12, 8, 7, 6, 5, 

Printing first element (column) of each row,

In [20]:
for row in intarray:
    print(row[0], end=', ')

9, 8, 

Array using for and range sentence,

In [21]:
np.array([n for n in range(1,30,2)])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## Creating arrays with ranges
Using arange to create an array of numbers from 0 to 7,

In [22]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

Numbers array from 3 to 8,

In [23]:
np.arange(3,7)

array([3, 4, 5, 6])

Numbers array from 12 to 3, descending every 3 numbers,

In [24]:
np.arange(12,2,-3)

array([12,  9,  6,  3])

lindspace is used to create non integer arrays, this is an array of 5 numbers (divided) between from 0 to 1,

In [25]:
np.linspace(0,1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

reshape is used to redimension of arrays, here is 1 dimension array from 21 to 2 with descending order,

In [26]:
np.arange(21,1,-1)

array([21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,
        4,  3,  2])

Now the same array with a shape of 5 columns and 4 rows,

In [27]:
np.arange(21,1,-1).reshape(4,5)

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

Using %timeit and random numbers in a list comprenhension to compare time processing between list an numpy array when its simulate 6 million dice roll,

In [28]:
import random
%timeit dicerolls = [random.randint(1,7) for i in range(0,6000000)]

2.82 s ± 84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Now using numpy, too much faster!

In [29]:
%timeit dicerolls = np.random.randint(1,7,6000000)

54.1 ms ± 864 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Math operations with arrays,


In [30]:
list1 = np.arange(2,16,2)
list1

array([ 2,  4,  6,  8, 10, 12, 14])

In [31]:
list1+10

array([12, 14, 16, 18, 20, 22, 24])

In [32]:
list1*3

array([ 6, 12, 18, 24, 30, 36, 42])

In [33]:
list1**(1/2)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739])

Substraction and division between arrays, only possible for arrays with the same shape and dimension,

In [34]:
list1 = np.arange(2,18,3)
list1

array([ 2,  5,  8, 11, 14, 17])

In [35]:
list2 = np.linspace(-2,20, num=6)
list2

array([-2. ,  2.4,  6.8, 11.2, 15.6, 20. ])

In [36]:
list2 - list1

array([-4. , -2.6, -1.2,  0.2,  1.6,  3. ])

In [37]:
list2 / list1

array([-1.        ,  0.48      ,  0.85      ,  1.01818182,  1.11428571,
        1.17647059])

It's also possible to compare each element of list,

In [38]:
list2<list1

array([ True,  True,  True, False, False, False])

Math functions  in numpy,

In [39]:
array1 = np.array( [[554,606,710,851],[1244,898,416,1763], [841,655,1105,1067]])
array1

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

In [40]:
array1.mean()

np.float64(892.5)

In [41]:
array1.sum()

np.int64(10710)

In [42]:
array1.min()

np.int64(416)

In [43]:
array1.max()

np.int64(1763)

Standard deviation,

In [44]:
array1.std()

np.float64(350.56656524355924)

Variance,

In [45]:
array1.var()

np.float64(122896.91666666667)

Is also possible to use these math functions for rows or colums, mean applied to columns,

In [46]:
array1.mean(axis=0)

array([ 879.66666667,  719.66666667,  743.66666667, 1227.        ])

mean applied to rows,

In [47]:
array1.mean(axis=1)

array([ 680.25, 1080.25,  917.  ])

## Indexig and slicing arrays
Sample array, sells,

In [48]:
sells = np.array ([[ 554, 606, 710, 851], [1244, 898, 416, 1763], [ 841, 655, 1105, 1067]])
sells

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

A single element, second row (index 1), first column (idnex 0),

In [49]:
sells[1,0]

np.int64(1244)

Rows 1 and 2 (from index 0 to index 1),

In [50]:
sells[0:2]

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763]])

Rows 2 and 3 (from index 1 to index 3),

In [51]:
sells[1:3]

array([[1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

Only first column elements,

In [52]:
sells[:,0]

array([ 554, 1244,  841])

Columns with index 0 and 2,

In [53]:
sells[:,[0,2]]

array([[ 554,  710],
       [1244,  416],
       [ 841, 1105]])

## Transpose
**reshape** function produces a copy of array with diferent shape,

In [54]:
sells1 = np.array([[ 500, 600, 550, 800], [1200, 800, 400,1000]])
sells1

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

From original 2 x 4 array to 1 x 8 array,

In [59]:
sells1.reshape(1,8)

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

In [58]:
sells1

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

**resize** function modifies the initial array, 

In [61]:
sells1.resize(1,8)

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

In [62]:
sells1

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

**.T (transpose)** function produces a copy of array and switches columns to rows,

In [63]:
sells1 = np.array([[ 500, 600, 550, 800], [1200, 800, 400,1000]])
sells1

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

In [64]:
sells1.T

array([[ 500, 1200],
       [ 600,  800],
       [ 550,  400],
       [ 800, 1000]])

In [65]:
sells1

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

## Pandas and series
A serie in pandas is a 1 dimension array able to store any type of data like integer, float, boolean, strings, lists in a single array. 

Library pandas must be imported,

In [5]:
import pandas as pd

Serie of integer numbers,

In [3]:
serie1 = pd.Series([160,256,98,108])
serie1

0    160
1    256
2     98
3    108
dtype: int64

Serie of 5 repeated element,

In [69]:
pd.Series(3.141,range(5))

0    3.141
1    3.141
2    3.141
3    3.141
4    3.141
dtype: float64

Getting an element (3rd element, index 2),

In [4]:
serie1[2]

np.int64(98)

Applying descriptive statistics methods to series,

In [5]:
serie1.mean()

np.float64(155.5)

In [6]:
serie1.describe()

count      4.000000
mean     155.500000
std       72.302605
min       98.000000
25%      105.500000
50%      134.000000
75%      184.000000
max      256.000000
dtype: float64

It's also possible to customize indexes, 

In [8]:
serie1 = pd.Series([160,256,98,108], index=['NY','CA','AZ','FL'])
serie1

NY    160
CA    256
AZ     98
FL    108
dtype: int64

Getting value of NY,

In [15]:
serie1['NY']

np.int64(160)

Now as a attribute,

In [16]:
serie1.NY

np.int64(160)

Another way to custom indexes,

In [17]:
serie1 = pd.Series({'NY':160, 'CA':256,'AZ':98,'FL':108})
serie1

NY    160
CA    256
AZ     98
FL    108
dtype: int64

Getting all descriptive statistics values,

In [18]:
serie1.describe()

count      4.000000
mean     155.500000
std       72.302605
min       98.000000
25%      105.500000
50%      134.000000
75%      184.000000
max      256.000000
dtype: float64

## DataFrames with Pandas
A dataframe is a two dimensional data structure or a table with rows and columns (like spreedsheet).

Dictonary to dataframe sample,

In [3]:
dic1 = {'NV':[68,67,66,65],'RI':[89,89,90,88], 'UT':[59,60,60,62],'TX':[70,68,67,65]}
dic1

{'NV': [68, 67, 66, 65],
 'RI': [89, 89, 90, 88],
 'UT': [59, 60, 60, 62],
 'TX': [70, 68, 67, 65]}

In [6]:
datafr1 = pd.DataFrame(dic1)
datafr1

NV  RI  UT  TX
0  68  89  59  70
1  67  89  60  68
2  66  90  60  67
3  65  88  62  65

It's also possible to change index on dataframes,

In [11]:
datafr1.index = ['Jan','Feb','Mar','Apr']
datafr1

NV  RI  UT  TX
Jan  68  89  59  70
Feb  67  89  60  68
Mar  66  90  60  67
Apr  65  88  62  65

Getting the column of TX,

In [33]:
datafr1['TX']

Jan    70
Feb    68
Mar    67
Apr    65
Name: TX, dtype: int64

Getting column as a attribute,

In [34]:
datafr1.TX

Jan    70
Feb    68
Mar    67
Apr    65
Name: TX, dtype: int64

loc and iloc to getting rows and slicing data. Getting 'Jan' row,

In [37]:
datafr1.loc['Jan']

NV    68
RI    89
UT    59
TX    70
Name: Jan, dtype: int64

Getting Feb row or index 1 (second row) with iloc,

In [39]:
datafr1.iloc[1]

NV    67
RI    89
UT    60
TX    68
Name: Feb, dtype: int64

Slicing Jan and Mar,

In [41]:
datafr1.loc[['Jan','Mar']]

NV  RI  UT  TX
Jan  68  89  59  70
Mar  66  90  60  67

Slicing Jan to Mar,

In [43]:
datafr1.loc['Jan':'Mar']

NV  RI  UT  TX
Jan  68  89  59  70
Feb  67  89  60  68
Mar  66  90  60  67

Slicing Feb to Apr for NV and TX,

In [45]:
datafr1.loc['Feb':'Apr',['NV','TX']]

NV  TX
Feb  67  68
Mar  66  67
Apr  65  65

## Boolean Indexes
Values higher than 70,

In [12]:
datafr1[datafr1>70]

NV  RI  UT  TX
Jan NaN  89 NaN NaN
Feb NaN  89 NaN NaN
Mar NaN  90 NaN NaN
Apr NaN  88 NaN NaN

Values between 65 and 80,

In [13]:
datafr1[(datafr1>=65) & (datafr1<=80)]

NV  RI  UT  TX
Jan  68 NaN NaN  70
Feb  67 NaN NaN  68
Mar  66 NaN NaN  67
Apr  65 NaN NaN  65

## Workign with specific cells values
Value of TX in Mar,

In [15]:
datafr1.at['Mar','TX']

np.int64(67)

Modifying values of TX in Mar,

In [16]:
datafr1.at['Mar','TX'] = 11
datafr1

NV  RI  UT  TX
Jan  68  89  59  70
Feb  67  89  60  68
Mar  66  90  60  11
Apr  65  88  62  65

## Descriptive statistic
Getting statistical results of most common statistics formulas, with describe function,

In [17]:
datafr1.describe()

NV         RI         UT         TX
count   4.000000   4.000000   4.000000   4.000000
mean   66.500000  89.000000  60.250000  53.500000
std     1.290994   0.816497   1.258306  28.407745
min    65.000000  88.000000  59.000000  11.000000
25%    65.750000  88.750000  59.750000  51.500000
50%    66.500000  89.000000  60.000000  66.500000
75%    67.250000  89.250000  60.500000  68.500000
max    68.000000  90.000000  62.000000  70.000000

Using a single statistic formula,

In [22]:
datafr1.mean()

NV    66.50
RI    89.00
UT    60.25
TX    53.50
dtype: float64

Setting to 2 decimal positions,

In [19]:
pd.set_option('display.precision',2)

In [21]:
datafr1.describe()

NV     RI     UT     TX
count   4.00   4.00   4.00   4.00
mean   66.50  89.00  60.25  53.50
std     1.29   0.82   1.26  28.41
min    65.00  88.00  59.00  11.00
25%    65.75  88.75  59.75  51.50
50%    66.50  89.00  60.00  66.50
75%    67.25  89.25  60.50  68.50
max    68.00  90.00  62.00  70.00

Use of traspose and traspose with mean formula,

In [23]:
datafr1.T

Jan  Feb  Mar  Apr
NV   68   67   66   65
RI   89   89   90   88
UT   59   60   60   62
TX   70   68   11   65

In [25]:
datafr1.T.describe()

Jan    Feb    Mar    Apr
count   4.00   4.00   4.00   4.00
mean   71.50  71.00  56.75  70.00
std    12.61  12.52  33.14  12.08
min    59.00  60.00  11.00  62.00
25%    65.75  65.25  47.75  64.25
50%    69.00  67.50  63.00  65.00
75%    74.75  73.25  72.00  70.75
max    89.00  89.00  90.00  88.00

In [26]:
datafr1.T.mean()

Jan    71.50
Feb    71.00
Mar    56.75
Apr    70.00
dtype: float64

## Sorting dataframe
Sorting dataframe by row index (descending alphabietically from Mar to Apri),

In [27]:
datafr1.sort_index(ascending=False)

NV  RI  UT  TX
Mar  66  90  60  11
Jan  68  89  59  70
Feb  67  89  60  68
Apr  65  88  62  65

Sorting dataframe by column index (ascending alphabietically from NV to UT),

In [28]:
datafr1.sort_index(axis=1)

NV  RI  TX  UT
Jan  68  89  70  59
Feb  67  89  68  60
Mar  66  90  11  60
Apr  65  88  65  62

Sorting numbers of a sliced single row (Jan),

In [29]:
datafr1.loc['Jan'].sort_values(ascending=False)

RI    89
TX    70
NV    68
UT    59
Name: Jan, dtype: int64