# NumPy Arrays

NumPy is python library used for working with multi dimensional arrays and matrices along with a large collection of mathematical functions to operate on these arrays.
## Array of data
Importing the library and creating the first array,

In [2]:
import numpy as np

In [3]:
factorial = np.array([1,2,6,24,120,720])
factorial

array([  1,   2,   6,  24, 120, 720])

Type of array,

In [4]:
type(factorial)

numpy.ndarray

Two dimensions array,

In [5]:
np.array([[3,4],[5,6],[7,8]])

array([[3, 4],
       [5, 6],
       [7, 8]])

List comprehension array with numpy,

In [6]:
np.array([n for n in range(1,30,2)])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## Array attributes
Working with 2 different types of arrays and dtype, shape, itemsize functions,

In [7]:
intarray = np.array([[9,10,11,12],[8,7,6,5]])
intarray

array([[ 9, 10, 11, 12],
       [ 8,  7,  6,  5]])

In [8]:
floatarray = np.array([[9**(1/2),10**(1/2),3.33],[10/3,3.4,3.03],[25,50,75]])
floatarray

array([[ 3.        ,  3.16227766,  3.33      ],
       [ 3.33333333,  3.4       ,  3.03      ],
       [25.        , 50.        , 75.        ]])

Type of array with dtype function,

In [9]:
intarray.dtype

dtype('int64')

In [10]:
floatarray.dtype

dtype('float64')

Dimension of array with ndim, dimension es about the amount of dimension of array, example: 
1 dimension = []
2 dimensions = [[],[]]
3 dimensions = [[[],[]],[[],[]]]

In [11]:
intarray.ndim

2

In [12]:
floatarray.ndim

2

Shape of array with shape function, shape is about the amount of columns and rows that the arrays has,

In [13]:
intarray.shape

(2, 4)

In [14]:
floatarray.shape

(3, 3)

Size and itemsize let to know the number of elements inside an array and the bytes to be stored,

In [15]:
intarray.size

8

In [16]:
intarray.itemsize

8

In [17]:
floatarray.size

9

In [18]:
floatarray.itemsize

8

Iterating with arrays, printing all elements,

In [19]:
for row in intarray:
    for elements in row:
        print(elements, end=', ')

9, 10, 11, 12, 8, 7, 6, 5, 

Printing first element (column) of each row,

In [20]:
for row in intarray:
    print(row[0], end=', ')

9, 8, 

Array using for and range sentence,

In [21]:
np.array([n for n in range(1,30,2)])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## Creating arrays with ranges
Using arange to create an array of numbers from 0 to 7,

In [22]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

Numbers array from 3 to 8,

In [23]:
np.arange(3,7)

array([3, 4, 5, 6])

Numbers array from 12 to 3, descending every 3 numbers,

In [24]:
np.arange(12,2,-3)

array([12,  9,  6,  3])

lindspace is used to create non integer arrays, this is an array of 5 numbers (divided) between from 0 to 1,

In [25]:
np.linspace(0,1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

reshape is used to redimension of arrays, here is 1 dimension array from 21 to 2 with descending order,

In [26]:
np.arange(21,1,-1)

array([21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,
        4,  3,  2])

Now the same array with a shape of 5 columns and 4 rows,

In [27]:
np.arange(21,1,-1).reshape(4,5)

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

Using %timeit and random numbers in a list comprenhension to compare time processing between list an numpy array when its simulate 6 million dice roll,

In [28]:
import random
%timeit dicerolls = [random.randint(1,7) for i in range(0,6000000)]

2.82 s ± 84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Now using numpy, too much faster!

In [29]:
%timeit dicerolls = np.random.randint(1,7,6000000)

54.1 ms ± 864 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Math operations with arrays,


In [30]:
list1 = np.arange(2,16,2)
list1

array([ 2,  4,  6,  8, 10, 12, 14])

In [31]:
list1+10

array([12, 14, 16, 18, 20, 22, 24])

In [32]:
list1*3

array([ 6, 12, 18, 24, 30, 36, 42])

In [33]:
list1**(1/2)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739])

Substraction and division between arrays, only possible for arrays with the same shape and dimension,

In [34]:
list1 = np.arange(2,18,3)
list1

array([ 2,  5,  8, 11, 14, 17])

In [35]:
list2 = np.linspace(-2,20, num=6)
list2

array([-2. ,  2.4,  6.8, 11.2, 15.6, 20. ])

In [36]:
list2 - list1

array([-4. , -2.6, -1.2,  0.2,  1.6,  3. ])

In [37]:
list2 / list1

array([-1.        ,  0.48      ,  0.85      ,  1.01818182,  1.11428571,
        1.17647059])

It's also possible to compare each element of list,

In [38]:
list2<list1

array([ True,  True,  True, False, False, False])

Math functions in numpy,

In [39]:
array1 = np.array( [[554,606,710,851],[1244,898,416,1763], [841,655,1105,1067]])
array1

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

In [40]:
array1.mean()

np.float64(892.5)

In [41]:
array1.sum()

np.int64(10710)

In [42]:
array1.min()

np.int64(416)

In [43]:
array1.max()

np.int64(1763)

Standard deviation,

In [44]:
array1.std()

np.float64(350.56656524355924)

Variance,

In [45]:
array1.var()

np.float64(122896.91666666667)

Is also possible to use these math functions for rows or colums, mean applied to columns,

In [46]:
array1.mean(axis=0)

array([ 879.66666667,  719.66666667,  743.66666667, 1227.        ])

mean applied to rows,

In [47]:
array1.mean(axis=1)

array([ 680.25, 1080.25,  917.  ])

## Indexig and slicing arrays
Sample array, sells,

In [48]:
sells = np.array ([[ 554, 606, 710, 851], [1244, 898, 416, 1763], [ 841, 655, 1105, 1067]])
sells

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

A single element, second row (index 1), first column (idnex 0),

In [49]:
sells[1,0]

np.int64(1244)

Rows 1 and 2 (from index 0 to index 1),

In [50]:
sells[0:2]

array([[ 554,  606,  710,  851],
       [1244,  898,  416, 1763]])

Rows 2 and 3 (from index 1 to index 3),

In [51]:
sells[1:3]

array([[1244,  898,  416, 1763],
       [ 841,  655, 1105, 1067]])

Only first column elements,

In [52]:
sells[:,0]

array([ 554, 1244,  841])

Columns with index 0 and 2,

In [53]:
sells[:,[0,2]]

array([[ 554,  710],
       [1244,  416],
       [ 841, 1105]])

## Transpose
**reshape** function produces a copy of array with diferent shape,

In [54]:
sells1 = np.array([[ 500, 600, 550, 800], [1200, 800, 400,1000]])
sells1

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

From original 2 x 4 array to 1 x 8 array,

In [59]:
sells1.reshape(1,8)

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

In [58]:
sells1

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

**resize** function modifies the initial array, 

In [61]:
sells1.resize(1,8)

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

In [62]:
sells1

array([[ 500,  600,  550,  800, 1200,  800,  400, 1000]])

**.T (transpose)** function produces a copy of array and switches columns to rows,

In [63]:
sells1 = np.array([[ 500, 600, 550, 800], [1200, 800, 400,1000]])
sells1

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

In [64]:
sells1.T

array([[ 500, 1200],
       [ 600,  800],
       [ 550,  400],
       [ 800, 1000]])

In [65]:
sells1

array([[ 500,  600,  550,  800],
       [1200,  800,  400, 1000]])

## Pandas and series
A serie in pandas is a 1 dimension array able to store any type of data like integer, float, boolean, strings, lists in a single array. 

Library pandas must be imported,

In [66]:
import pandas as pd

Serie of integer numbers,

In [68]:
serie1 = pd.Series([160,256,98,108])
serie1

0    160
1    256
2     98
3    108
dtype: int64

Serie of 5 repeated element,

In [69]:
pd.Series(3.141,range(5))

0    3.141
1    3.141
2    3.141
3    3.141
4    3.141
dtype: float64